import React, { Component } from 'react'
import { Route, Link } from 'react-router-dom'
import AuthenticatedRoute from '../auth/components/AuthenticatedRoute'
import Header from '../header/Header'
import SignUp from '../auth/components/SignUp'
import SignIn from '../auth/components/SignIn'
import SignOut from '../auth/components/SignOut'
import ChangePassword from '../auth/components/ChangePassword'
import DisplayPublic from '../components/DisplayPublic.js'
import DisplayPrivate from '../components/DisplayPrivate.js'
import Post from '../components/Create.js'
import Update from '../components/Update.js'
import apiUrl from '../apiConfig.js'
import SpeciesEntry from '../components/SpeciesEntry'
